site_name: Finansowy GPS
theme:
  name: material
  language: pl
  palette:
    - scheme: default
      primary: green
      accent: light green
      toggle:
        icon: material/card-bulleted-settings-outline
        name: Przełącz na tryb ciemny
    - scheme: slate
      primary: green
      accent: light green
      toggle:
        icon: material/card-bulleted-settings
        name: Przełącz na tryb jasny
  features:
    - navigation.tabs
    - content.code.copy
nav:
  - Strona Główna: index.md
  - Autorzy: autorzy.md
  - Teoria Finansów: teoria.md
  - Przykłady (Case Study): przyklady.md
  - Weryfikacja i Testowanie: testowanie.md